version: '3'
services:
  app:
    container_name: backend
    build: 
      context: goproject
      dockerfile: Dockerfile
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - ./goproject:/app'
    depends_on:
      - fullstack-postgres          
    networks:
      - fullstack
    image: 0637281961/backend

  react:
    build: 
      context: ecommerce-pro
      dockerfile: Dockerfile
    restart: always
    tty: true
    ports: 
      - "3000:3000"
    command: npm start
    container_name: frontend
    volumes:
      - './ecommerce-pro:/app'
    networks:
      - fullstack
    image: 0637281961/frontend
    
  fullstack-postgres:
    image: 0637281961/postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=postgres  
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=test
      - DATABASE_HOST=fullstack-postgres
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - fullstack
    
  pgadmin:
    image: 0637281961/backenddpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: live@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - fullstack-postgres
    ports:
      - "5050:80"
    networks:
      - fullstack
    restart: unless-stopped

volumes:
  api:
  database_postgres:                  

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge